### ISSUE TITLE
Error when creating project with empty collaborators list.

### ISSUE THREAD

**Issue by jgwerner** [3Blades/app-backend#115]
Creating a project with an empty collaborators list returns a 405 error. Although the collaborators parameter is optional, the error code should describe why request is being rejected. And tell the user that if the collaborators list is empty then the collaborators parameter should not be added.

Furthermore if a collaborator is added but the user does not exist (typo or not exist at user) then the endpoint should return a message stating that the user is unknown. This could probably solve the first scenario above, for example `User string does not exist.`

**Comment by jkp85** [comment]
Already fixed.
