### ISSUE TITLE
Unable to start server with interfaces other than CLI Tools.

### ISSUE THREAD

**Issue by jgwerner** [3Blades/app-backend#116]
Unable to start the server with Swagger interactive docs or `cURL`. CLI Tools can create the server successfully using `POST /{namespace}/projects/{project_pk}/servers/{id}/start/` endpoint.

Furthermore, there is no response besides the 201 status code. I suggest returning the endpoints and a message stating whether or not the server was successfully started, in addition to the status code.

**Comment by raygesualdo** [comment]
I am unable to start a server even using the CLI tools.

**Comment by jgwerner** [comment]
@jkp85 I see that there are tests for creating server resources [here](https://github.com/3Blades/app-backend/blob/master/servers/tests/test_spawners.py#L82) and testing starting a server [here](https://github.com/3Blades/app-backend/blob/master/servers/tests/test_spawners.py#L100). Please help us fix tests so that they error out when not working (such as is the case now).

**Comment by jkp85** [comment]
@jgwerner @raygesualdo It should be fixed here: https://github.com/3Blades/app-backend/commit/1f6baf5dce6ebf9a1181f14c5e7dfe35b8cae4a8 Did you use `DJANGO_SETTINGS_MODULE=appdj.settings.test` as settings module?

**Comment by jgwerner** [comment]
@jkp85 no, is that Test config necessary fornservers to start even with Swagger interactive docs?

**Comment by jkp85** [comment]
Sorry I thought that you couldn't launch tests. I will check it out.

**Comment by jgwerner** [comment]
@jkp85 @johngriebel @raygesualdo @roachmd Verified that it works with updated images.

**Comment by jgwerner** [comment]
Done.
