### ISSUE TITLE
Logs streaming API return 404 for stopped servers

### ISSUE THREAD

**Issue by raygesualdo** [3Blades/app-backend#119]
This is the same issue we had with the status WS endpoint. When pinging a server's logs websocket URL, if the server is already stopped, a 404 error is returned instead of allowing the websocket to connect. If the server is already running, the websocket connects without an issue.

**Comment by jkp85** [comment]
I cannot reproduce. There is an issue when server was not started after creation, but i don't see the way to connect to logs websocket when there is nothing to listen. I checked via cli tools and browser and it's connecting to stopped server.

**Comment by johngriebel** [comment]
@raygesualdo Is this still occurring?

**Comment by johngriebel** [comment]
Closing due to no response.
