### ISSUE TITLE
User guide for updating Swagger docs from source

### ISSUE THREAD

**Issue by jgwerner** [3Blades/app-backend#130]
We are using various third party tools to display API documentation based on Swagger. In most cases, these third party tools support importing `swagger.json` and create documentation automatically. 

However, we need documentation that will allow us to document the API at its source so when swagger.json is created it already has all necessary documentation, such as descriptions, examples, etc.

cc/ @johngriebel @jkp85

**Comment by johngriebel** [comment]
Closing as no longer applicable/complete in the openapi repo.
