### ISSUE TITLE
Update Readme and env file with environment variables

### ISSUE THREAD

**Issue by jgwerner** [3Blades/app-backend#131]
Update environment variables file (env) so that it contains all [base environment variables](https://github.com/3Blades/app-backend/blob/master/appdj/settings/base.py). 

Some are environment variables that were already there but were not added to env file. Others are new, specifically those that deal with search.

Update README accordingly.

**Comment by johngriebel** [comment]
@jgwerner Are additional changes coming for this issue, or can it be closed?
