### ISSUE TITLE
Integrate search

### ISSUE THREAD

**Issue by jgwerner** [3Blades/app-backend#135]
Integrate search into API.

@jkp85 @johngriebel need to create the specification. Search should be implicit when `GET` operations are handled by the backend. Do you think there is a need for a specific search endpoint?

3blades/3blades#76

**Comment by jkp85** [comment]
@jgwerner We talked about it here 3Blades/app-backend#126 and we concluded that one search endpoint is best. Implementation was merged here 3Blades/app-backend#129

**Comment by johngriebel** [comment]
@jgwerner @jkp85 Can this be closed then?

**Comment by jkp85** [comment]
@johngriebel I think so
