### ISSUE TITLE
Implement File Watcher

### ISSUE THREAD

**Issue by johngriebel** [3Blades/app-backend#146]
Using Facebook's [Watchman](https://facebook.github.io/watchman/) tool, implement a file watcher that will monitor the workspaces directory, and handle any changes accordingly. 
[3blades/issue #75](https://github.com/3Blades/3blades/issues/75)

**Comment by jgwerner** [comment]
@johngriebel @roachmd re opening to handle config issues.

**Comment by roachmd** [comment]
@johngriebel @jgwerner 

Created a release for 3blades

https://github.com/3Blades/watchman/releases/download/v4.7.0-3blades/watchman

**Comment by jgwerner** [comment]
@roachmd what are the instructions to run the release?

**Comment by roachmd** [comment]
@jgwerner Working on that.

**Comment by johngriebel** [comment]
Done.
