### ISSUE TITLE
Add base URL for API version

### ISSUE THREAD

**Issue by jgwerner** [3Blades/app-backend#161]
Add base URL for API version.

Instead of:

    https://staging.3blades.io/auth/jwt-token-auth/

Endpoint should be something like:

    https://staging.3blades.io/v1.0/auth/jwt-token-auth/

**Comment by johngriebel** [comment]
Per discussion elsewhere, it is agreed that each major version will have its own instance. All sub-versions will be directed to the same instance. For example:
- 1.0, 1.1, 1.2, etc. traffic all goes to v1 server
- 2.0, 2.1, 2.2, etc. traffic all goes to v2 server

and so on.
