### ISSUE TITLE
Websocket endpoints not returing output

### ISSUE THREAD

**Issue by jgwerner** [3Blades/app-backend#164]
Streaming API endpoints are not pushing information to clients. Tested with UI and validated unsuccessful connection with Chromes developer tools.

Necessary for streaming logs and server status.

**Comment by jkp85** [comment]
Fixed. I recently added new env var to app-backend `TBS_HTTPS` it has to be set to `true` for every deployment that uses https. After adding it logs and stream endpoints sheme is `wss` and then it works. I already added this to staging env file. I remember it was present yesterday.

**Comment by jkp85** [comment]
@jgwerner I'm testing this on staging and it's working. Javascript object type that is returned is `Blob`. It may seem like it's not returning anything, but you need to read it in proper way, ex:
```javascript
var ws = new WebSocket("websocket_uri");
ws.onmessage = function(data) {
	var reader = new FileReader();
	reader.onload = function() {
		console.log(reader.result);
	}
	reader.readAsText(data.data);
}
```
This is how docker is doing it. We simply proxy this from docker over openresty:
https://github.com/3Blades/openresty/blob/master/nginx.conf#L87
I also noticed that there is no `TBS_HTTPS` env var is missing. I remember putting it there yesterday. It should be `true` for every deployment where https is used. I added it to staging env file and now everything is working ok.
