### ISSUE TITLE
Not able to open a notebook in the UI after creation.

### ISSUE THREAD

**Issue by roachmd** [3Blades/app-backend#191]
## General Support

Not able to open  a notebook after creation.

![backend_url](https://user-images.githubusercontent.com/5784681/28034907-a7428b5c-6580-11e7-9495-db86c86de7a1.gif)

**Comment by jgwerner** [comment]
Tests conducted:

- Fresh install with on-premise scripts 
- Launch and attempt to connect with react-frontend from localhost pointing to fresh install.
- Launch and attempt to connect with CLI Tools 

Unfortunately not a lot of additional information was available with logs.

**Comment by jgwerner** [comment]
Fixed with proper release of OpenResty.
