### ISSUE TITLE
Not able to access billing endpoint

### ISSUE THREAD

**Issue by pthakkar230** [3Blades/app-backend#194]
Trying to access the url: _https://dev-api.3blades.ai/namespace/billing/cards/

Tried namespaces:
apitester: http://dev-api.3blades.ai/apitester/billing
foo: http://dev-api.3blades.ai/foo/billing

Getting a 404 error: page not found
Cannot do API tests on Runscope for Billing until this is resolved.

Related to #198

**Comment by johngriebel** [comment]
My guess would be that the `ENABLE_BILLING` environment variable is not set to true. This will result in all billing URLs being unavailable on that instance.
