### ISSUE TITLE
Add avatar upload and update endpoint

### ISSUE THREAD

**Issue by jgwerner** [3Blades/app-backend#195]
User profile endpoint includes an option to get user's avatar from a URL. We need a separate endpoint for uploading and updating Avatar.

3blades/3blades#84

**Comment by jgwerner** [comment]
@johngriebel @jkp85 we would need to discuss validation, too. Perhaps these validations can also be enforced client-side before the image is sent to the backend in the first place.

**Comment by raygesualdo** [comment]
Agreed on the validation. We can do file type validation (I suggest we limit to JPG and PNG only) and file size validation (I suggest we start at 100k, maybe less since we're not doing any image processing to it).
