### ISSUE TITLE
Not able to add project collaborator

### ISSUE THREAD

**Issue by pthakkar230** [3Blades/app-backend#210]
I am getting an error 500 when trying to add a collaborator. I tried adding "foo" and "apitester" as collaborators, and I get an error 500. If I add any nonexistent user like "yellow", it will tell me that user doesn't exist.

Runscope Log: https://www.runscope.com/radar/vzxz7svfdhxu/891bcee9-ca15-4f2d-84f0-80fbabef4195/history/2d063325-c9de-427a-a0dd-16403096da1c

You can also see the error by accessing this endpoint:  https://dev-api.3blades.ai/v1/admin/projects/60ecfcfc-2469-4cda-9997-74c9ca5125aa/collaborators/ 

To Reproduce: Add collaborator with username such as "foo" or "apitester" (created users).

**Comment by johngriebel** [comment]
@pthakkar230 The fix for this has been merged. Can you redeploy and test?

**Comment by pthakkar230** [comment]
Tested, it's working. Closing issue.

**Comment by pthakkar230** [comment]
There seems to be an issue with updating the collaborator with `PUT` or `PATCH`. It says `can't set attribute`. Seems like a minor issue, but am reopening issue for now. 

https://www.runscope.com/radar/vzxz7svfdhxu/891bcee9-ca15-4f2d-84f0-80fbabef4195/history/5f8f5173-d5b2-4972-a720-a6c80f803a33

**Comment by johngriebel** [comment]
Updating is not a valid operation for Collaborators. The correct workflow is to delete the old one, and a create a new one with the desired permissions, etc.
