### ISSUE TITLE
Testing Refresh JWT Token endpoint through Runscope

### ISSUE THREAD

**Issue by pthakkar230** [3Blades/app-backend#212]
Trying to test `jwt-token-refresh` endpoint through Runscope. It requires the existing JWT web token to generate a new one. However, it has a 30 day expiration period, and the endpoint gives an error to refresh the token within the 30 day period. 

To Reproduce:
1. Use this link to generate token: http://dev-api.3blades.ai/auth/jwt-token-auth/
2. Login using username and password and click POST
3. Copy generated JWT token
4. Go to this endpoint:  https://dev-api.3blades.ai/auth/jwt-token-refresh/
5. Paste the generated JWT token from previous link and click POST
6. You should see `orig-iat` error

Any input on how to change that 30 day period to allow for testing of this endpoint?

**Comment by johngriebel** [comment]
Closing.
