### ISSUE TITLE
Integrations endpoint doesn't exist for users

### ISSUE THREAD

**Issue by pthakkar230** [3Blades/app-backend#214]
Cannot access integrations endpoint defined by docs referenced here: 
https://docs.3blades.io/v1.1/reference#users_integrations_list-1

Using dev environment

To reproduce: 
1. Go to https://dev-api.3blades.ai/v1/users/profiles/   
2. Copy the "id" of the user you want to use
3. Go to this link: https://dev-api.3blades.ai/v1/users/`id`/integrations    >> Replace id with the id you copied
4. You should see 404 error

Is this a bug or is the endpoint wrong? If the endpoint is wrong, we have to update docs.

**Comment by johngriebel** [comment]
@pthakkar230, the correct endpoint (for now) is `https://dev-api.3blades.ai/v1/users/integrations`. Meaning that a client can only access integrations owned by the currently authorized user. 

Perhaps that should not be the case. If we would like to allow access to these integrations across users, then the endpoint you listed would be correct. 

This should be discussed, cc: @jgwerner, @jkp85

**Comment by pthakkar230** [comment]
Using the `https://dev-api.3blades.ai/v1/users/integrations`, there is still an error 500 regarding a missing `user_id`

**Comment by johngriebel** [comment]
@pthakkar230 yeah, the fix hasn't been merged yet.

**Comment by johngriebel** [comment]
@pthakkar230 The fix for this has been merged, you can test after the next deployment.

**Comment by johngriebel** [comment]
Per discussion, this issue is now fixed.
