### ISSUE TITLE
API key and SSH key errors in users 

### ISSUE THREAD

**Issue by pthakkar230** [3Blades/app-backend#215]
Getting an error for the following endpoints in users from the API: "Retrieve account's API key", "Reset a user's API key", "Retrieve a SSH key", and "Recreate an SSH key".

Using dev environment:

**To Reproduce:**

1. Go to https://dev-api.3blades.ai/v1/users/profiles/
2. Copy the "id" of the user you want to use
3. Go to the following links:
https://dev-api.3blades.ai/v1/users/'id'/api-key/
https://dev-api.3blades.ai/v1/users/'id'/ssh-key/

>> Replace 'id' with the id you copied

4. The exact error should be `unexpected keyword argument 'version'`

5. Go to the following links:
https://dev-api.3blades.ai/v1/users/'id'/api-key/reset/
https://dev-api.3blades.ai/v1/users/'id'/ssh-key/reset/

>> Replace 'id' with the id you copied

6. The links in the previous step require the 'id' you copied earlier. Paste them and click POST.
7. You should see error ""detail": "CSRF Failed: CSRF token missing or incorrect."

Is the endpoint incorrect or is their information missing?

**Comment by johngriebel** [comment]
@pthakkar230, perhaps it is not documented correctly but as of right now, authorization endpoints are not included under the versioning scheme, so if you remove `v1` from your URLs, things should work fine.

**Comment by pthakkar230** [comment]
I am just getting a 404 error without `v1`

**Comment by johngriebel** [comment]
Hmm. Okay.

**Comment by johngriebel** [comment]
@pthakkar230 Fix for this has been merged - you can re-deploy and test.
