### ISSUE TITLE
Endpoint errors

### ISSUE THREAD

**Issue by jgwerner** [3Blades/app-backend#217]
After creating a new resource and starting the server the user cannot access started server with provided enpdoint. Additionally, the Logs are not streaming due to endpoint errors.

Developer tools in Chrome provide this information:

```
index.js:38 WebSocket connection to 'wss://dev-api.3blades.ai/admin/projects/8f58ea26-8ea0-40df-a551-b6a95d4e6a00/servers/8bd6d5eb-fd98-4aa7-9547-4fa9e99394be/status/' failed: Error during WebSocket handshake: Unexpected response code: 404
```

This screen shot depicts behavior:

![jupyter_access_error](https://user-images.githubusercontent.com/920170/28278528-6d762166-6aeb-11e7-9f90-dbb3d37482f0.gif)

API backend is latest: https://dev-api.3blades.ai.

**Comment by johngriebel** [comment]
Fixed by the referenced pull requests. Closing.
