### ISSUE TITLE
Cannot access customer data when creating new customer (Billing)

### ISSUE THREAD

**Issue by pthakkar230** [3Blades/app-backend#228]
While creating a customer through Runscope, you get a success code of 201. However, when you try to `GET` that data or update it through `PUT` or `PATCH`, it gives a 404 error saying 

`{"detail": "Not found."}`

I am able to `DELETE` the customer however.

Here is the Runscope log: https://www.runscope.com/radar/vzxz7svfdhxu/3afc327b-12c9-4dc6-bd96-0c7c8dd867a4/history/689c85ae-11a7-4007-b6b0-88448e349ac7

Input on how to fix this would be great.

**Comment by johngriebel** [comment]
@pthakkar230 It seems like for your Customer `PUT` test, you're accidentally using the `cards` endpoint. Also note that Card objects are associated with a Customer and not a User. It appears that you are passing a User id in this test. I've created a PR to fix the issues for `GET`/`PUT`/`PATCH`.

**Comment by johngriebel** [comment]
Note that the `TRAVIS_PULL_REQUEST` environment variable must be set to `false` to avoid hitting the pretend Stripe classes. This isn't quite as simple as adding it to the `env` file though because that could mess with the Travis builds. This will require some thought.

**Comment by raygesualdo** [comment]
@johngriebel I think it's a little dangerous to depend on `TRAVIS_PULL_REQUEST` so much in the code. I don't think it's wrong to run conditionals against it, but we might want to abstract out the check where we can change it in just one place. I know it's mostly localized to the billing app, but still. Thoughts?

**Comment by jgwerner** [comment]
@johngriebel @raygesualdo how about:

```
if [ "$TRAVIS_PULL_REQUEST" == "true" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
  git clone https://github.com/3blades/stripe-test-classes
  cp stripe-test-classes/. ../copy_to_wherever
fi
```
This way we could effectively replace staging/production classes with dev classes and just switch the key in the env vars file. 

Does that make sense?

**Comment by jkp85** [comment]
@raygesualdo We don't have access to hidden travis env variables in pull requests. I suggested that we can mock things that need those hidden env vars but only in PRs. If you build master then they are not mocked. Any suggestions how we can access stripe api without revealing our tokens?

**Comment by johngriebel** [comment]
@raygesualdo Like @jkp85 said, the reason this has been coded this way is that we don't have access to our stripe API key in PRs. I agree that I'm not a fan of relying on `TRAVIS_PULL_REQUEST` in the code, but we needed to get the build working and this was the best (read: quickest) solution at the time. I'm thinking about how this could be refactored to only rely on the check once, or do something like @jgwerner said. The ideal solution though, like @jkp85 pointed out, is to have access to our stripe API key during PR builds.

**Comment by pthakkar230** [comment]
Tested fix to above issue, it is working now. This issue can be closed when a solution is found to the `TRAVIS_PULL_REQUEST` env variable.

**Comment by johngriebel** [comment]
@raygesualdo @jkp85 @jgwerner @roachmd Perhaps the best solution is to not depend _directly_ on `TRAVIS_PULL_REQUEST`, but some other environment variable we create. Then, in `travis.yml` we can check `TRAVIS_PULL_REQUEST`, and set `FAKE_STRIPE` (or whatever) accordingly. Then, we can leave `FAKE_STRIPE` defaulted to True, and not have to worry about interfering with Travis builds. Thoughts?
