### ISSUE TITLE
Cannot access hosts endpoint

### ISSUE THREAD

**Issue by pthakkar230** [3Blades/app-backend#230]
Trying to reach `hosts` endpoint for API testing. I am using the `dev` environment. Here is the link:

http://dev-api.3blades.ai/v1/admin/hosts/

I get an `502 Bad Gateway` error from `nginx` when I hit that endpoint.

**Comment by johngriebel** [comment]
@pthakkar230 I am unable to reproduce this error. Can you confirm that it is still occurring?

**Comment by pthakkar230** [comment]
This is what is happening. Before I try to create a host, this endpoint works: https://dev-api.3blades.ai/v1/admin/hosts/. After I run the test, that same endpoint breaks with the `502 Bad Gateway` error.

https://www.runscope.com/radar/vzxz7svfdhxu/627e7450-6890-4512-ba04-ce9d9b61557e/history/b3067ec0-b779-4e55-9418-e9017d1e49e7

To reproduce:
1. Go to http://dev-api.3blades.ai/v1/admin/hosts/
2. Fill in the parameters and click POST
3. You should see error.

**Comment by johngriebel** [comment]
I think this is a matter of setting valid parameters for the `POST` request, and/or an issue with Docker. Perhaps @jkp85 can help.
