### ISSUE TITLE
Update API endpoints

### ISSUE THREAD

**Issue by jgwerner** [3Blades/app-backend#24]
We need to update our endpoints to support:

- **Optional namespaces**: this would help us not have to maintain separate endpoints for different namespace types, the user would just have implicit access (or not) depending on the role they authenticated with.
- **Add subsystem placeholder in endpoint**: would help us add more subsystems later without having to roll out breaking changes to endpoints
```
POST /api/app/v1/[namespace/]model/(uuid)/start/
```
- **Actions**: actions should represent object created by users, so that we can obtain streaming logs, satuses, etc just like we do for job and model servers. If response is immediate, `Success` or `Failed` state should be returned. If operation is async, response should return `202 Accepted` with `In progress` state and then should change to success or failed state after. Return schema should have resource URI of created action. 
  - Attributes: resource_uri, uuid, object, action, method, path, user, user_agent, start_date, end_date, state, ip, location, is_user_action, can_be_cancelled, can_be_retired
- **Events**: should be created every time an object is created or changes state. 
  - Attributes: type (job, model, datasource, file, etc), action, parents (server, action - object to which the action is applied to), resource_uri, state, uuid, datetime
- **Errors**: document error codes better

cc @netoisc @rmorshea @jkp85

**Comment by jkp85** [comment]
HTTP methods overview:

- HEAD should be the same as GET, the only difference is that there is no response body. How is it useful then? User can check if resource exists by only checking response status. We can also provide last modified header.
- PUT is for creating new record or replace a record with URL that contain resource ID ex. http://example.com/api/user/1/ will create user with ID 1 if it does not exists or replaces user info of user with ID 1. PUT method is idempotent, meaning that you can perform this several times and the outcome will be the same.
- PATCH method is for updating part of a resource. Ex. updating only user email or password. We don't have to provide multiple endpoints for this kind of tasks, only one. User can only send `{"email": "jdoe@example.com"}` and that's it, she don't have to send all user info.

HEAD and PATCH methods used properly can help us with lowering amount of data transferred.

**Comment by jgwerner** [comment]
- We decided to make namespaces obligatory.
- Added Triggers
- Will continue with more detailed error code documentation

**Comment by AbhishikthaReddy** [comment]
@3Blades/cli-tools
