### ISSUE TITLE
Getting a user email address by id doesn't return anything

### ISSUE THREAD

**Issue by pthakkar230** [3Blades/app-backend#241]
This is a very minor issue, just thought it would be good to point out for sake of documentation. Right now, you can create an user email address, but when you try to access that email address by id through `GET`, it doesn't return any values. It just returns an empty body. 

https://www.runscope.com/radar/vzxz7svfdhxu/f19644a0-548c-45f1-9529-b55c5a71b5dd/history/3d7e2414-ed79-4421-9b29-c6a3a07aae89

To see response, scroll down to `Get user email address`. There isn't even an error from this test, so it is very minor.

**Comment by johngriebel** [comment]
Here's what is happening:
- The "Create a new user email" test is sending a `POST` to `/v1/users/<some_user_id>/emails/`. However, the Email record is created for the `admin` user, not the user associated with `some_user_id`. This is the correct behavior, as you should not be able to create emails for other users.
- The `GET` test assumes that the Email record has been created under the `some_user_id` User, and of course it is not found.

**Comment by johngriebel** [comment]
The test has been fixed and confirmed working. Closing.
