### ISSUE TITLE
Add project information to server JSON payload

### ISSUE THREAD

**Issue by raygesualdo** [3Blades/app-backend#268]
Currently, the serializer for Servers, there is no information about the project to which the server belongs. Included in the server's JSON payload should be the ID, name and owner name of parent project.

**Comment by jkp85** [comment]
@raygesualdo Why do you need those information? Project id is part of server endpoint, you can fetch project details with that. I think adding project information to server will result in bloated response. I can understand that for specific use case you need that, but you will receive this data every time you will fetch any server.
