### ISSUE TITLE
Re-Design Triggers API

### ISSUE THREAD

**Issue by johngriebel** [3Blades/app-backend#276]
Currently, triggers are exposed as a top level endpoint and provide too much flexibility to the end user. Triggers should be a sub-endpoint of things such as servers, projects, etc. For now, we will only implement server triggers, and do so like this:

`/v1/{namespace}/projects/{project_id}/servers/{server_id}/trigger/`
`/v1/{namespace}/projects/{project_id}/servers/{server_id}/trigger/{id}/`

For more information, see [openapi/97](https://github.com/3Blades/openapi/issues/97).

**Comment by jkp85** [comment]
@jgwerner @johngriebel So firstly we plan to create triggers for server actions - start and terminate? What is the user story here?
