### ISSUE TITLE
Issue starting Resource { server } Prod-blue-green as a new user

### ISSUE THREAD

**Issue by roachmd** [3Blades/app-backend#295]
Can't start server from a new superuser or Admin. Original foo user seem to work.

![issue8](https://user-images.githubusercontent.com/5784681/28944111-523bed7c-786f-11e7-815b-c826a46ac488.gif)

**Comment by jkp85** [comment]
@roachmd It has been fixed, you need to update app-backend and docker-events containers.

**Comment by johngriebel** [comment]
@roachmd has the fix for this been validated yet? would like to close the issue if so.

**Comment by johngriebel** [comment]
Validated as fixed in Slack convo. Closing.
