### ISSUE TITLE
Fix simple authentication token endpoint

### ISSUE THREAD

**Issue by jgwerner** [3Blades/app-backend#309]
Endpoint `/simple-token-auth/` not responding correctly. Validate whether or not it is necessary. If so, then backend should respond correctly to POSTs.

cc/ @jkp85 @johngriebel

**Comment by jkp85** [comment]
@jgwerner `/simple-token-auth/` is just for debugging purposes. It should be only available on dev instances.

**Comment by johngriebel** [comment]
Closing.
