### ISSUE TITLE
Eliminate requirement for token parameter for credit card replacements and updates

### ISSUE THREAD

**Issue by jgwerner** [3Blades/app-backend#321]
When leaving the token field blank when using `PUT` and `PATCH` methods with `/v1/namespace/billing/cards/id/` endpoint, backend returns:

```
{
  "token": [
    "This field may not be blank."
  ]
}
```

We should eliminate this requirement and only enforce the use of the token parameter using `POST` method.

**Comment by johngriebel** [comment]
Done.
