### ISSUE TITLE
Initial Backend Implementation of Notifications

### ISSUE THREAD

**Issue by johngriebel** [3Blades/app-backend#365]
Part of 3blades/3blades#127.

As outlined in the linked epic, notifications should be sent for the following events:

- Billing Related Events
    - [ ] Enrollments (stripe.customer.subscription.created)
    - [ ] Charges (stripe.charge.succeeded or invoice.payment_succeeded)
    - [ ] Failed Payments (stripe.charge.failed)
    - [ ] Cancellations (stripe.customer.subscription.deleted)
    - [ ] Trial Expiry (stripe.customer.subscription.trial_will_end)
        - Stripe only sends this 3 days before trial period is set to end. Not ideal. Could perhaps use upcoming invoice + subscription.status. If status is 'TRIALING`, create notification.

This implementation should also include namepsace (global) level settings:
- [ ] Turn notifications on or off altogether
- [ ] Turn emails on and off. Emails can only be enabled if notifications are enabled.

More situations will eventually require notifications as well, but those will be opened as separate issues after this first pass. 

When a notification is generated, it should be sent to the user as an email. The user should have the ability to opt out of emails of course. In the future, it may be nice to allow users to select which notifications they do and do not receive emails for. 

The "Notifications Center in UI" portion of the epic is solely a frontend issue, provided that there is a database table with notifications, and a column similar to `read` that indicates whether or not the user has viewed the notifications. 

Users should be able to configure notifications to send webhooks as well. Presumably, we can make use of our existing triggers framework to do this.

It seems like the [django-notifications](https://github.com/django-notifications/django-notifications) library will be useful with some tweaking.

**Comment by jgwerner** [comment]
@johngriebel to start we should add standard server state changes to notifications, including `error` state. So to start it would be:

- Server created
- Server started
- Server stopped
- Server terminated
- Server errored

With `Server Errored` we could send stack trace to notifications webhook or email.

I would also add that it would be nice to push out webhook notifications and emails since webhooks are so common and allow for easy integrations with third parties.

**Comment by johngriebel** [comment]
@jgwerner I included a brief bit about webhooks. My thinking in omitting notifications for server created, started, stopped, and terminated was that those are user generated actions, that the user should know about but I think I agree. For instance, if a collaborator on a project did something to stop my server, I may want to know about it.

**Comment by jgwerner** [comment]
@johngriebel yes, and in some cases these servers would change state based on Triggers.

**Comment by johngriebel** [comment]
Note that `python manage.py loaddata notification_types.json` will have to be added to all deployment jobs.
