### ISSUE TITLE
Updating a credit card errors when optional fields are passed with empty values

### ISSUE THREAD

**Issue by raygesualdo** [3Blades/app-backend#367]
When one hits `PATCH /{namespace}/billing/cards/{id}` and passes optional fields (e.g. `address_line2`) with `null` or empty string values, a `400` error is returned with the following payload:

```
{
  "address_line2":[
    "This field may not be blank."
  ]
}
```

**Comment by johngriebel** [comment]
@raygesualdo On second thought, I'm not sure we should allow blank values to be passed. How can the backend know when a blank or null value should be ignored instead of overwriting the existing value?

**Comment by johngriebel** [comment]
@raygesualdo any thoughts on this?
