### ISSUE TITLE
UI cannot delete collaborator

### ISSUE THREAD

**Issue by elijah2352** [3Blades/app-backend#377]
When we try to delete a collaborator using the UI (demo version), it doesn't delete them.  It also doesn't even try to delete them. It just does nothing. The front-end is hitting the endpoint correctly, so we believe it is a backend problem.

**Comment by raygesualdo** [comment]
Specifically, the UI is getting a `404` error when trying to delete the collaborator.

**Comment by johngriebel** [comment]
Verified as fixed as of build no. 635.
