### ISSUE TITLE
Add All Foreign Keys to API Payloads

### ISSUE THREAD

**Issue by johngriebel** [3Blades/app-backend#419]
When serializing database objects to include in a response, we should include all foreign keys in the payload. Only the primary key is required in the payload but existing code that currently returns more information should remain the same.

Webhooks are the primary impetus for this change. For example, if I have set up a webhook to be delivered when a server is started currently I would not get any information about the project that the server belongs to. It is easy to envision a scenario where I would want this information, and there is no (good) way to get it currently.

**Comment by nathanielcompton** [comment]
Merge into production, 10 Nov 2017
