### ISSUE TITLE
Automatically Populate ServerSize Model

### ISSUE THREAD

**Issue by johngriebel** [3Blades/app-backend#444]
We should create a fixtures file in the `servers` app to allow the auto-population of Server Sizes.
It should contain the following server sizes:
- `nano`: 512 MB
- `small`: 1024 MB
- `medium`: 2048 MB
- `large`: 4096 MB
~~- `x-large`: 8192 MB~~ (removed this option per PR recommendation)

Since some of these server size records may already exist in some environments but not others, perhaps it is best to write a script that for each size checks if it exists, and if not, creates it.

**Comment by nathanielcompton** [comment]
Related PR available at: https://github.com/3Blades/app-backend/pull/537

**Comment by nathanielcompton** [comment]
Per PR comment, updating this ticket to remove the `x-large` server option

**Comment by nathanielcompton** [comment]
Merged into master 11/14/17
