### ISSUE TITLE
Define Notification Email Templates

### ISSUE THREAD

**Issue by johngriebel** [3Blades/app-backend#445]
Currently, all notification email templates are blank. We should at least define a plain text version.

- [ ] payment failed
- [ ] payment success
- [ ] subscription canceled
- [ ] subscription created
- [ ] trial ended
- [ ] trial will end

**Comment by jgwerner** [comment]
@jgriebel, here you go.

### payment failed

Hello {user.name},

Unfortunately we had issues charging your credit card for the account 3Blades.

Here's the message we received from our payment provider: {stripe.error}

No worries if this is just a temporary failure. We'll try charging your card again in 1 day.

Should your credit card have changed, you can update your card details any time.

All the best, 

The 3Blades Team


### payment success

Hi {user.name},

Thank you for {account.name} payment to Bill.com. The credit/debit card you have on file with us was successfully charged {subscription.amount} for the billing period {start.date} - {end.date}. To view your statement of fees, log in at our website and navigate https://3blades.ai/settings/billing.

Have questions? Sign in at our website, then contact us with the chat widget.

All the best,

The 3Blades Team


### subscription canceled

Hi {user.name},

You have successfully removed your monthly subscription from 3Blades and have been downgraded to the free plan. Please remember that you can always upgrade your plan again at any time in the future.
 
All the best,
 
The 3Blades Team

### subscription created

Hi {account.name},

We’re glad to have you on board with us!
 
Thank you for upgrading your subscription. We are here to help, contact us anytime by logging into the application and clicking on the chat widget.

All the best,

The 3Blades Team

### trial ended

Hi {user.name},

Thank you for taking 3Blades for a spin! Your free trial has now ended, and you won't be able to launch any new servers. However, you will continue to have access to your projects and files.

Subscribe today if you would like to continue to use our service.

All the best, 

The 3Blades Team

### trial will end

Hello {user.name},

Just a reminder that your free trial ends tomorrow and your account {account.name} will be automatically charged for the first month of service. If you have not update your billing information, then your account will downgrade to the free version.

Our team is available to help you with anything you need. Contact us anytime by logging into our application and clicking on the chat widget, we are here to help!

All the best,

The 3Blades Team
