### ISSUE TITLE
Avatars should have https, not http.

### ISSUE THREAD

**Issue by jgwerner** [3Blades/app-backend#505]
Avatars are downloaded using http. This causes some alerts or could cause some errors with https sessions.

```
react-dom.production.min.js:67 Mixed Content: The page at 'https://deploy-preview-348--threeblades-webui-green.netlify.com/greg2/NotificationsTest/resources/bff978ba-1782-4937-b351-9daaf3b4efcc' was loaded over HTTPS, but requested an insecure image 'http://api.3blades.ai/media/greg2/avatar/me1_sm.jpeg'. This content should also be served over HTTPS.
```

Error is also in current production deployment:

```
Mixed Content: The page at 'https://app.3blades.ai/' was loaded over HTTPS, but requested an insecure image 'http://api.3blades.ai/media/greg2/avatar/me1_sm.jpeg'. This content should also be served over HTTPS.
```

**Comment by nathanielcompton** [comment]
This issue should have been fixed with the merging of the `to_representation()` method located at:
https://github.com/3Blades/app-backend/blob/master/users/serializers.py#L27

Closing this issue now, and will remain the point of contact in case the issue happens again in the future.
