### ISSUE TITLE
Getting 404s for most project URLs

### ISSUE THREAD

**Issue by raygesualdo** [3Blades/app-backend#520]
Below is the error I get from Django:

![image](https://user-images.githubusercontent.com/5465958/32513654-c3f81a7c-c3c8-11e7-926a-438574e11733.png)
![image](https://user-images.githubusercontent.com/5465958/32513662-cbc66e20-c3c8-11e7-9aa8-83345a485af4.png)

**Comment by johngriebel** [comment]
Fixed by #520.
