### ISSUE TITLE
Search is very broken

### ISSUE THREAD

**Issue by raygesualdo** [3Blades/app-backend#547]
**Description**
Symptoms include:
- results include objects with `null` as the value for every key
- results do not return the correct results, e.g. using the search query "apitester" does not actually return the `apitester` user
- capitalized search queries seem to prevent any results from being returned
- it may be due to the above issues, but recently created projects don't show in search results

We need to either get our current search implementation working or look at 3rd-party services ([Algolia](https://www.algolia.com/)).

**Environment**
Dev

**Comment by johngriebel** [comment]
Related to 3blades/3blades#180

**Comment by johngriebel** [comment]
[Integrating Algolia with Django](https://www.algolia.com/apps/C5HDI7GDCP/dashboard)

**Comment by johngriebel** [comment]
It turns out that Algolia isn't a practical solution for a number of reasons. I'm looking into alternatives.

**Comment by johngriebel** [comment]
Apparently, this is a well-known issue with Haystack. They provide some[ possible solutions](https://django-haystack.readthedocs.io/en/master/signal_processors.html) in their documentation.
