### ISSUE TITLE
Cleanup README, Document env vars

### ISSUE THREAD

**Issue by johngriebel** [3Blades/app-backend#553]
Since we no longer support on-premises, we can remove the section in `README.md` regarding environment variables. However, we should document all environment variables in a wiki page.

**Comment by johngriebel** [comment]
Instead of placing these definitions in a wiki, let's create another markdown file and define them there. This will allow us better control of this documentation.

**Comment by nathanielcompton** [comment]
Let's add a `/docs/` dir for internal documentation

**Comment by nathanielcompton** [comment]
PR available at: https://github.com/3Blades/app-backend/pull/564
