### ISSUE TITLE
FIX :: No Longer getting launch for notebooks.

### ISSUE THREAD

**Issue by roachmd** [3Blades/app-backend#562]
The notebook show started after a page refresh. However, I'm not getting a launch button

![screen shot 2017-11-29 at 10 02 46 am](https://user-images.githubusercontent.com/5784681/33381653-9886edd4-d4ec-11e7-9c29-c995083a702b.png)

**Comment by raygesualdo** [comment]
This is because the status syntax changed from "Running" to "RUNNING". Can you create an issue in react-frontend for me to ignore capitalization on status checks?

**Comment by jkp85** [comment]
@raygesualdo This is probably how aws is returning a status. I will handle that on my side. It should be `Running`

**Comment by johngriebel** [comment]
@jkp85 I see that you pushed a commit for this. Do we need a PR?

**Comment by jkp85** [comment]
@johngriebel Not yet, something is off with my commits. I will create another PR.
