### ISSUE TITLE
Slack integration

### ISSUE THREAD

**Issue by jkp85** [3Blades/app-backend#71]
This particular integration will be handled by triggers. General workflow is this:

- user wants to send a message after certain event occurs (ex. seirver stopped)
- user needs to connect his slack account with our service via OAuth2
- user creates trigger with server stop action
- a microservice is listening docker events, when stop event happens microservice is sending an stop action
- trigger launches and sends notification to slack via slack api

**Comment by jgwerner** [comment]
@jkp @johngriebel we could leverage AWS SNS + Lambda for some of this. There are pros and cons but we should discuss tomorrow. Pros reduced code base to maintain, proven stability. Cons quasi vendor lock-in and reduced flexibility for on-premise installs.
