### ISSUE TITLE
Triggers

### ISSUE THREAD

**Issue by jkp85** [3Blades/app-backend#72]
## Trigger types
There can be two types of triggers:
- Fired at scheduled time (cron tasks)
- Fired after certain event occurs

## Implementation details.

Triggers are tightly coupled with Actions. Action is anything performed by user or our system.

### Data model
- Schedule - Cron schedule
- Effect - action to trigger
- Cause - action that launches an effect

### Trigger cycle

1. User creates trigger by specifying schedule or cause and effect (action to perform).
    - schedule is cron entry (ex. "0 1 * * *")
    - cause is an action created by specifying an object (like server) and an action (like stop)
    - effect is an action created similar to cause by specifying object (like slack message), an action (like send) and optional payload (message text).
Both cause and effect are actions that are created in the process of creating trigger object. Those actions state is "Created". In other words actions are prepared to be launched.
2. When scheduled time comes or cause action change state then django signal is sent that triggers an effect. Effect is triggered by sending http request to effect path.
3. Another two action objects are created that are copies of original cause and effect. Those new actions replaces actions that were performed.

This cycle can be chained, which means that you can set up a workflow where one action triggers another and that another action triggers third and so on. You can also create a tree where one action triggers two other actions and so on.

@jgwerner @johngriebel @AbhishikthaReddy What do you think? Creating UI can be a challenge, but in my opinion possibility to chain and tree actions can grant us a way to set up pre-built data analysis workflows.

**Comment by jgwerner** [comment]
@jkp sounds good. We could allow the user to chain and tree actions with webhooks. At the CLI Tools or UI level that should be easy enough to implement.
