### ISSUE TITLE
Use native web sockets from docker daemon to enable streaming logs

### ISSUE THREAD

**Issue by jgwerner** [3Blades/app-backend#91]
Gliderlabs' Logspout is not optimal anymore since new versions of the docker deamon allow more stable TCP connections to obtain streaming syslogs.

Therefore we have decided to deprecate the use of logspout and use docker deamon directly to stream logs via **Streaming API**.

**Comment by jgwerner** [comment]
@jkp85 should this issue be closed then? It was linked to PR #88

**Comment by jkp85** [comment]
@jgwerner Yes this can be closed.

**Comment by jgwerner** [comment]
Closing time!
